name: opentoonix-http-server
version: '3.9'

services:
  mysql:
    image: mysql:8
    restart: always
    container_name: opentoonix_mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USERNAME}

  http-server:
    image: opentoonix-http-server
    container_name: opentoonix_http-server
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      AVATAR_STORAGE_FOLDER_PATH: ${AVATAR_STORAGE_FOLDER_PATH}
      DATABASE_HOST: mysql
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: 3306
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ${LOCAL_AVATAR_STORAGE_FOLDER_PATH}:${AVATAR_STORAGE_FOLDER_PATH}
