version: '3.1'

services:

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    depends_on:
      - mysql
    environment:
      AVATAR_STORAGE_FOLDER_PATH: /app/avatars
      DATABASE_HOST: mysql
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: 3306
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      JWT_SECRET: ${JWT_SECRET}
      KEYSTORE_PATH: ${KEYSTORE_PATH}
      KEYSTORE_PASSWORD: ${KEYSTORE_PASSWORD}
      KEYSTORE_TYPE: ${KEYSTORE_TYPE}
    volumes:
      - avatars:/app/avatar

volumes:
    mysql:
    avatars: